name: Build EXE with Nuitka

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka ordered-set zstandard

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka your_script.py --standalone --onefile --disable-console --output-dir=dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-exe
          path: dist/your_script.exe

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/your_script.exe
